name: Build macOS Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Xcode
      run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

    - name: Build with Xcode
      run: |
        xcodebuild -scheme Whoah -configuration Release -derivedDataPath build -disableAutomaticPackageResolution | xcbeautify

    - name: Archive Artifacts
      run: |
        cd build/Build/Products/Release
        zip -r artifacts.zip *  # Cria um arquivo ZIP com os artefatos de build

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: macOS-artifacts
        path: build/Release/artifacts.zip
