name: Build Whoah-Math for macOS and Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build with Xcode
      run: |
        xcodebuild -scheme Whoah -configuration Release -derivedDataPath build -disableAutomaticPackageResolution | xcbeautify

    - name: Archive Artifacts
      run: |
        cd build/Build/Products/Release
        zip -r Whoah-Math.zip *
        mv Whoah-Math.zip $GITHUB_WORKSPACE/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Whoah Math - macOS
        path: Whoah-Math.zip

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Ninja
      run: choco install ninja

    - name: Install CMake
      run: choco install cmake

    - name: Configure with CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_CXX_FLAGS_RELEASE="-static-libgcc -static-libstdc++" --preset release

    - name: Build with CMake
      run: |
        cd build
        cmake --build . --config Release

    - name: Archive Artifacts
      run: |
        cd build/
        $zipPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "Whoah-Math.zip"
        Compress-Archive -Path . -DestinationPath $zipPath

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Whoah Math - Windows
        path: Whoah-Math.zip
