name: Build Whoah-Math for macOS and Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build with Xcode
      run: |
        xcodebuild -scheme Whoah -configuration Release -derivedDataPath build -disableAutomaticPackageResolution | xcbeautify

    - name: Archive Artifacts
      run: |
        cd build/Build/Products/Release
        zip -r Whoah-Math.zip *
        mv Whoah-Math.zip $GITHUB_WORKSPACE/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Whoah Math - macOS
        path: Whoah-Math.zip

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Ninja
      run: |
        choco install ninja

    - name: Install CMake
      run: |
        choco install cmake

    - name: Configure with CMake
      run: |
        mkdir build
        cd build
        cmake .. --preset release

    - name: Build with CMake
      run: |
        cd build
        cmake --build . --config Release

    - name: Copy DLLs
      run: |
        $dlls = @(
            "libstdc++-6.dll",
            "libgcc_s_seh-1.dll"
        )
        foreach ($dll in $dlls) {
            $src = "C:/tools/msys64/mingw64/bin/$dll"
            $dst = "build/Release/$dll"
            Copy-Item $src -Destination $dst
        }

    - name: Archive Artifacts
      run: |
        cd build/Release
        Compress-Archive -Path . -DestinationPath Whoah-Math.zip
        Move-Item Whoah-Math.zip $env:GITHUB_WORKSPACE

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Whoah Math - Windows
        path: Whoah-Math.zip
