name: Build macOS and Windows Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Xcode
      run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

    - name: Build with Xcode
      run: |
        xcodebuild -scheme Whoah -configuration Release -derivedDataPath build -disableAutomaticPackageResolution | xcbeautify

    - name: Archive Artifacts
      run: |
        cd build/Build/Products/Release
        zip -r artifacts.zip *
        mv artifacts.zip $GITHUB_WORKSPACE/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macOS-artifacts
        path: artifacts.zip

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Ninja
      run: |
        choco install ninja

    - name: Set up CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Ninja" || exit 1  # Usando Ninja como gerador

    - name: Build with CMake
      run: |
        cd build
        cmake --build . --config Release || exit 1  # Certifique-se de estar no diretório correto

    - name: Archive Artifacts
      run: |
        cd build/Release
        zip -r artifacts.zip *
        mv artifacts.zip $GITHUB_WORKSPACE/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-artifacts
        path: artifacts.zip
