name: Build macOS Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Xcode
      run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

    - name: Build with Xcode
      run: |
        xcodebuild -scheme Whoah -configuration Release -derivedDataPath build -disableAutomaticPackageResolution | xcbeautify

    - name: Archive Artifacts
      run: |
        cd build/Build/Products/Release
        zip -r artifacts.zip *  # Cria um arquivo ZIP com os artefatos de build

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macOS-artifacts
        path: build/Build/Products/Release/artifacts.zip

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 16 2019" -A x64  # Ajuste o gerador e arquitetura conforme necessário

    - name: Build with CMake
      run: |
        cmake --build . --config Release

    - name: Archive Artifacts
      run: |
        cd Release
        zip -r artifacts.zip *  # Cria um arquivo ZIP com os artefatos de build

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-artifacts
        path: artifacts.zip
