name: Build Whoah-Math

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        build_type: [Release]
        cpp_compiler: [cl]

    steps:
    - uses: actions/checkout@v4

    - name: Install Homebrew for x86_64
      if: runner.os == 'macos-latest'
      run: |
        sudo rm -rf /opt/homebrew
        arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Install xcbeautify
      if: runner.os == 'macos-latest'
      run: |
        arch -x86_64 /usr/local/bin/brew install xcbeautify

    - name: Install GMP for x86_64
      if: runner.os == 'macos-latest'
      run: |
        arch -x86_64 /usr/local/bin/brew install gmp

    - name: Set reusable strings
      if: runner.os != 'macos-latest'
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          echo "artifact-name=Whoah Math - Windows" >> "$GITHUB_OUTPUT"
          echo "executable-path=${{ github.workspace }}\\build\\Release\\Whoah-Math.exe" >> "$GITHUB_OUTPUT"
        fi

    - name: Install MSYS2
      if: runner.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: mingw-w64-x86_64-toolchain

    - name: Install GMP on Windows
      if: runner.os == 'windows-latest'
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm mingw-w64-x86_64-gmp

    - name: Configure CMake
      if: runner.os != 'macos-latest'
      run: |
        cmake -B ${{ steps.strings.outputs.build-output-dir }} \
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
        -S ${{ github.workspace }} \
        -DCMAKE_PREFIX_PATH=/usr/local

    - name: Build with Xcode
      if: runner.os == 'macos-latest'
      run: |
        xcodebuild -scheme Whoah -configuration Release -derivedDataPath build \
          ARCHS=x86_64 \
        | xcbeautify

    - name: Build-CMake
      if: runner.os != 'macos-latest'
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Archive Artifacts
      if: runner.os == 'macos-latest'
      run: |
        cd build/Build/Products/Release
        zip -r Whoah-Math.zip Whoah-Math
        mv Whoah-Math.zip $GITHUB_WORKSPACE/

    - name: Upload Artifacts macOS
      if: runner.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: Whoah Math - macOS
        path: Whoah-Math.zip
    
    - name: Upload Artifact Windows
      if: runner.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.strings.outputs.artifact-name }}
        path: ${{ steps.strings.outputs.executable-path }}
